export const INSERT_PSEUDOCODE = [
  "función insertar(clave):",
  "  hoja = buscarHoja(raíz, clave)",
  "  hoja.claves.agregar(clave)",
  "  hoja.claves.ordenar()",
  "",
  "  si hoja.claves.tamaño == 3:",
  "    dividir(hoja)",
  "",
  "función dividir(nodo):",
  "  medio = nodo.claves[1]",
  "  izq = nuevo Nodo([nodo.claves[0]])",
  "  der = nuevo Nodo([nodo.claves[2]])",
  "",
  "  si nodo == raíz:",
  "    nueva_raíz = nuevo Nodo([medio])",
  "    nueva_raíz.hijos = [izq, der]",
  "    raíz = nueva_raíz",
  "  si no:",
  "    padre.claves.agregar(medio)",
  "    padre.reemplazarHijo(nodo, [izq, der])",
  "",
  "    si padre.claves.tamaño == 3:",
  "      dividir(padre)",
] as const;

export const INSERT_LINE = {
  buscarHoja: 1,
  agregar: 2,
  ordenar: 3,
  checkOverflow: 5,
  dividirCall: 6,
  dividirHeader: 8,
  split: 9,
  esRaiz: 13,
  nuevaRaiz: 14,
  siNo: 17,
  padreAgregar: 18,
  padreReemplazar: 19,
  checkPadreOverflow: 21,
  dividirPadre: 22,
};

export const DELETE_PSEUDOCODE = [
  "función eliminar(clave):",
  "  nodo = buscar(raíz, clave)",
  "",
  "  si nodo es hoja:",
  "    nodo.claves.eliminar(clave)",
  "    si nodo.claves.tamaño == 0:",
  "      corregirUnderflow(nodo)",
  "  si no:",
  "    sucesor = minimoDeSubárbol(hijoDerechoDeClave(nodo, clave))",
  "    nodo.claves.reemplazar(clave, sucesor.claves[0])",
  "    eliminar(sucesor.claves[0])",
  "",
  "función corregirUnderflow(nodo):",
  "  hermano = hermanoCon2Claves(nodo)",
  "",
  "  si hermano existe:",
  "    redistribuir(nodo, hermano)",
  "  si no:",
  "    fusionar(nodo, hermano, padre)",
  "    si padre.claves.tamaño == 0:",
  "      corregirUnderflow(padre)",
] as const;

export const DELETE_LINE = {
  buscar: 1,
  esHoja: 3,
  eliminarClave: 4,
  checkUnderflow: 5,
  corregirUnderflowCall: 6,
  siNoInterno: 7,
  sucesor: 8,
  reemplazarSucesor: 9,
  eliminarSucesor: 10,
  corregirUnderflowHeader: 12,
  hermano: 13,
  siHermanoExiste: 15,
  redistribuir: 16,
  siNoFusion: 17,
  fusionar: 18,
  checkPadreVacio: 19,
  corregirUnderflowPadre: 20,
};
